POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "20821641-6591-4384-bac8-1c90cb92a3a3"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a5057467-076b-4bd8-b900-be0c0cb9fb06",
    "account_id_to": "b755bff6-cb51-432e-b1eb-e8d601c959c1",
    "amount": 50
}
